server:
  port: 8080
websocket:
  server:
    port:9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/netty_chatroom?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
    driverClassName: com.mysql.jdbc.Driver
    username: "root"
    password: "0000"
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: -1
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
